### ISSUE TITLE
Adjusting brightness

### ISSUE THREAD

**Issue by JoshuaOJones** [nervus/FutabaVFD#2]
Is there anyway to adjust the brigtness on this display? When I first turn it on it lights up super bright, then dulls down. How can I change this? Is there a command for this? @nervus  @per1234

**Comment by nervus** [comment]
Hi,

I don’t know of actual commands that change brightness via the interface provided by the display.

However, it might be possible to add some PWC pins to control the anode voltage of the display like described in 7.2 and 7.3 of this :

https://www.noritake-elec.com/technology/general-technical-information/vfd-operation

Hope it helps.

Best,
Mircea
